/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.*;
import javax.swing.JPopupMenu.Separator;

/**
 *
 * @author aamir
 */
public class Forgetpassword extends javax.swing.JFrame {

    /**
     * Creates new form Forgetpassword
     */
    Connection conn = null;
    ResultSet rs;
    PreparedStatement pst; 
    public String id = "6";
    CardLayout cardlayout;
    public Forgetpassword() {
        conn = ConnectDB.dbConnector();
        initComponents();
        //enterPassword();      
        System.out.println(id);
        cardlayout = (CardLayout)(MainCard.getLayout());
        cardlayout.show(MainCard, "card2");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MainCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        fnameedit = new javax.swing.JTextField();
        lnameedit = new javax.swing.JTextField();
        emailedit = new javax.swing.JTextField();
        phoneedit = new javax.swing.JTextField();
        jobedit = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fnameLabel = new javax.swing.JLabel();
        lnameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        jobLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idedit = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        MainCard.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(254, 254, 254));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 6, 108)));

        fnameedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fnameeditKeyTyped(evt);
            }
        });

        lnameedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lnameeditKeyPressed(evt);
            }
        });

        emailedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emaileditKeyTyped(evt);
            }
        });

        phoneedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneeditKeyTyped(evt);
            }
        });

        jobedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jobeditKeyTyped(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Fname:*");

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Lname:*");

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Email   :*");

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Phone :*");

        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Job       :*");

        fnameLabel.setForeground(new java.awt.Color(255, 0, 0));
        fnameLabel.setText("*missmatch");

        lnameLabel.setForeground(new java.awt.Color(255, 0, 0));
        lnameLabel.setText("*missmatch");

        emailLabel.setForeground(new java.awt.Color(255, 0, 0));
        emailLabel.setText("*missmatch");

        phoneLabel.setForeground(new java.awt.Color(255, 0, 0));
        phoneLabel.setText("*missmatch");

        jobLabel.setForeground(new java.awt.Color(255, 0, 0));
        jobLabel.setText("*missmatch");

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("ID:*");

        idedit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ideditKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ideditKeyPressed(evt);
            }
        });

        idLabel.setForeground(new java.awt.Color(255, 0, 0));
        idLabel.setText("*missmatch");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jobedit, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(phoneedit, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(emailedit))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(idedit)
                                    .addComponent(fnameedit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(lnameedit, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(fnameLabel)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(idLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idLabel))
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fnameedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fnameLabel))
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(17, 17, 17)
                                            .addComponent(lnameLabel))
                                        .addComponent(lnameedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(emailLabel))
                                    .addComponent(emailedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(phoneLabel))
                            .addComponent(phoneedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(17, 17, 17)
                            .addComponent(jobLabel))
                        .addComponent(jobedit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MainCard.add(jPanel2, "card2");

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 51, 199)));
        jPanel4.setOpaque(false);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_filled_cancel_32px.png"))); // NOI18N
        jLabel7.setText("jLabel4");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("Reset Password");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jLabel8))
        );

        jButton1.setBackground(new java.awt.Color(2, 8, 135));
        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton1.setText("Reset");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(12, 23, 185), 1, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainCard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MainCard, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       /*JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter a password:");
        JPasswordField pass = new JPasswordField(10);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Enter Password",
                         JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                         null, options, options[1]);
        if(option == 0) // pressing OK button
        {
            char[] password = pass.getPassword();            
            String getPassword = new String(password);
            if ("maxamed".equals(getPassword)){
            System.out.println("Your password is: " + getPassword);                
            }
        } 
        */
        
        String sql = "select * from Employee where emp_Number =?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            rs = pst.executeQuery();
            while(rs.next()){
                String fname = rs.getString("fname");
                String lname =rs.getString("lname");
                String type = rs.getString("Job_Description");
                String phone = rs.getString("Mobile");
                String email = rs.getString("email");
                if(fname.equals(fnameedit.getText())&&lname.equals(lnameedit.getText())&& email.equals(emailedit.getText())&&phone.equals(phoneedit.getText())&&type.equals(jobedit.getText())){
                    //cardlayout.show(MainCard, "card2");
                    JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter a password:");
        JPasswordField pass = new JPasswordField(10);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Enter Password",
                         JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                         null, options, options[1]);
        if(option == 0) // pressing OK button
        {
            char[] password = pass.getPassword();            
            String getPassword = new String(password);
            //update password
            String sql4="UPDATE `Employee` SET `Pin`= ? WHERE `emp_Number`=?";
            try{
                Forgetpassword f = new Forgetpassword();
                pst = conn.prepareStatement(sql4);
                pst.setString(1, getPassword);
                pst.setString(2, id);
                pst.execute();

                JOptionPane.showMessageDialog(null,"Recovery Done");
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
        } 
                }
            }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fnameeditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fnameeditKeyTyped
        
        String sql = "select * from Employee where emp_Number =?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            rs = pst.executeQuery();
            while(rs.next()){
                String fname = rs.getString("fname");
                String lname =rs.getString("lname");
                String type = rs.getString("Job_Description");
                String phone = rs.getString("Mobile");
                String email = rs.getString("email");
                if(fname.equals(fnameedit.getText())&& fname.length()==fnameedit.getText().length()){
                    fnameLabel.setText("Matched");
                    fnameLabel.setForeground(Color.GREEN);                    
                }
                else if(!fname.equals(fnameedit.getText())){
                    fnameLabel.setText("Missmatch");
                    fnameLabel.setForeground(Color.RED);
                }
                else{
                    fnameLabel.setText("Missmatch");
                    fnameLabel.setForeground(Color.RED);
                }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_fnameeditKeyTyped

    private void lnameeditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lnameeditKeyPressed
        String sql = "select * from Employee where emp_Number =?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            rs = pst.executeQuery();
            while(rs.next()){
                String fname = rs.getString("fname");
                String lname =rs.getString("lname");
                String type = rs.getString("Job_Description");
                String phone = rs.getString("Mobile");
                String email = rs.getString("email");
                if(lname.equals(lnameedit.getText())&& lname.length()==lnameedit.getText().length()){
                    lnameLabel.setText("Matched");
                    lnameLabel.setForeground(Color.GREEN);                    
                }
                else if(!lname.equals(lnameedit.getText())){
                    lnameLabel.setText("Missmatch");
                    lnameLabel.setForeground(Color.RED);
                }
                else{
                    lnameLabel.setText("Missmatch");
                    lnameLabel.setForeground(Color.RED);
                }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_lnameeditKeyPressed

    private void emaileditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emaileditKeyTyped
       String sql = "select * from Employee where emp_Number =?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            rs = pst.executeQuery();
            while(rs.next()){
                String fname = rs.getString("fname");
                String lname =rs.getString("lname");
                String type = rs.getString("Job_Description");
                String phone = rs.getString("Mobile");
                String email = rs.getString("email");
                if(email.equals(emailedit.getText())&& email.length()==emailedit.getText().length()){
                    emailLabel.setText("Matched");
                    emailLabel.setForeground(Color.GREEN);                    
                }
                else if(!email.equals(emailedit.getText())){
                    emailLabel.setText("Missmatch");
                    emailLabel.setForeground(Color.RED);
                }
                else{
                    emailLabel.setText("Missmatch");
                    emailLabel.setForeground(Color.RED);
                }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_emaileditKeyTyped

    private void phoneeditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneeditKeyTyped
        String sql = "select * from Employee where emp_Number =?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            rs = pst.executeQuery();
            while(rs.next()){
                String fname = rs.getString("fname");
                String lname =rs.getString("lname");
                String type = rs.getString("Job_Description");
                String phone = rs.getString("Mobile");
                String email = rs.getString("email");
                if(phone.equals(phoneedit.getText())&& phone.length()==phoneedit.getText().length()){
                    phoneLabel.setText("Matched");
                    phoneLabel.setForeground(Color.GREEN);                    
                }
                else if(!phone.equals(phoneedit.getText())){
                    phoneLabel.setText("Missmatch");
                    phoneLabel.setForeground(Color.RED);
                }
                else{
                    phoneLabel.setText("Missmatch");
                    phoneLabel.setForeground(Color.RED);
                }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_phoneeditKeyTyped

    private void jobeditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jobeditKeyTyped
        String sql = "select * from Employee where emp_Number =?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            rs = pst.executeQuery();
            while(rs.next()){
                String fname = rs.getString("fname");
                String lname =rs.getString("lname");
                String type = rs.getString("Job_Description");
                String phone = rs.getString("Mobile");
                String email = rs.getString("email");
                if(type.equals(jobedit.getText())&& type.length()==jobedit.getText().length()){
                    jobLabel.setText("Matched");
                    jobLabel.setForeground(Color.GREEN);                    
                }
                else if(!type.equals(jobedit.getText())){
                    jobLabel.setText("Missmatch");
                    jobLabel.setForeground(Color.RED);
                }
                else{
                    jobLabel.setText("Missmatch");
                    jobLabel.setForeground(Color.RED);
                }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jobeditKeyTyped

    private void ideditKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ideditKeyTyped
        String sql = "select * from Employee where emp_Number =?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, idedit.getText());
            rs = pst.executeQuery();
            while(rs.next()){
                String acc = rs.getString("emp_Number");
                String lname =rs.getString("lname");
                String type = rs.getString("Job_Description");
                String phone = rs.getString("Mobile");
                String email = rs.getString("email");
                if(acc.equals(idedit.getText())&& acc.length()==idedit.getText().length()){
                    idLabel.setText("Matched");
                    idLabel.setForeground(Color.GREEN);   
                    
                    id = idedit.getText();
                    idedit.setEditable(false);
                    
                }
                else if(!acc.equals(idedit.getText())){
                    idLabel.setText("Missmatch");
                    idLabel.setForeground(Color.RED);
                }
                else{
                    idLabel.setText("Missmatch");
                    idLabel.setForeground(Color.RED);
                }
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_ideditKeyTyped

    private void ideditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ideditKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ideditKeyPressed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        
        this.dispose();
        
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgetpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forgetpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainCard;
    private javax.swing.JLabel emailLabel;
    public javax.swing.JTextField emailedit;
    private javax.swing.JLabel fnameLabel;
    private javax.swing.JTextField fnameedit;
    private javax.swing.JLabel idLabel;
    public javax.swing.JTextField idedit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jobLabel;
    private javax.swing.JTextField jobedit;
    private javax.swing.JLabel lnameLabel;
    private javax.swing.JTextField lnameedit;
    private javax.swing.JLabel phoneLabel;
    public javax.swing.JTextField phoneedit;
    // End of variables declaration//GEN-END:variables

    private void enterPassword() {
        JPanel panel = new JPanel();
        JLabel label = new JLabel("Enter a ID:");
        JTextField pass = new JTextField(10);
        panel.add(label);
        panel.add(pass);
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Account Number",
                         JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE,
                         null, options, options[1]);
        if(option == 0) // pressing OK button
        {
            id = pass.getText();
            idedit.setText(id);
        }
        else{
            System.exit(0);
        }
    }
}
