package Gui;


import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aamir
 */
public class Loan extends javax.swing.JFrame {

    /**
     * Creates new form VerifyAccount
     */
    String av_balance;
    Connection conn = null;
    PreparedStatement pst;
    Statement stmt = null;
    ResultSet rs;
    String gender,s;
    JFileChooser jfc;
    File file;
    public Loan() {
        conn = ConnectDB.dbConnector();
        initComponents();
        editammount.setText("0");
        SelectAll_customer();
        //getIdAll_customer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        editfname = new javax.swing.JTextField();
        editlname = new javax.swing.JTextField();
        editammount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        acc_no = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fnameguarantors = new javax.swing.JTextField();
        lnameguarantors = new javax.swing.JTextField();
        emailguarantors = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        phoneguarantors = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        addressguarantors = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cityguarantors = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        age_guarontores = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        dateguarantors = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(1, 16, 233), 3));

        jLabel2.setFont(new java.awt.Font("Ubuntu Thin", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 5, 122));
        jLabel2.setText("LOAN Application");

        jButton1.setBackground(new java.awt.Color(255, 3, 0));
        jButton1.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setText("Accept");
        jButton1.setOpaque(true);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_filled_cancel_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Loan Applicant's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(1, 1, 1))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(1, 1, 1));
        jPanel2.setOpaque(false);

        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("first name");

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("last name");

        editfname.setForeground(new java.awt.Color(1, 1, 1));
        editfname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        editfname.setOpaque(false);

        editlname.setForeground(new java.awt.Color(1, 1, 1));
        editlname.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        editlname.setOpaque(false);

        editammount.setForeground(new java.awt.Color(1, 1, 1));
        editammount.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        editammount.setOpaque(false);

        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("Ammount requested for $");

        jLabel3.setForeground(new java.awt.Color(5, 0, 0));
        jLabel3.setText("Account Number");

        acc_no.setBackground(new java.awt.Color(254, 254, 254));
        acc_no.setForeground(new java.awt.Color(0, 7, 91));
        acc_no.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ID" }));
        acc_no.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 2, 73), 2, true));
        acc_no.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                acc_noItemStateChanged(evt);
            }
        });
        acc_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_noActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(editammount)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(editfname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(editlname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(acc_no, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(acc_no, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editlname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editammount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Guarantor's  Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(1, 1, 1))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(1, 1, 1));
        jPanel3.setOpaque(false);

        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("first name");

        jLabel11.setForeground(new java.awt.Color(1, 1, 1));
        jLabel11.setText("last name");

        fnameguarantors.setForeground(new java.awt.Color(1, 1, 1));
        fnameguarantors.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        fnameguarantors.setOpaque(false);

        lnameguarantors.setForeground(new java.awt.Color(1, 1, 1));
        lnameguarantors.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        lnameguarantors.setOpaque(false);

        emailguarantors.setForeground(new java.awt.Color(1, 1, 1));
        emailguarantors.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        emailguarantors.setOpaque(false);

        jLabel12.setForeground(new java.awt.Color(1, 1, 1));
        jLabel12.setText("Email");

        jLabel13.setForeground(new java.awt.Color(1, 1, 1));
        jLabel13.setText("Phone Number");

        phoneguarantors.setForeground(new java.awt.Color(1, 1, 1));
        phoneguarantors.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        phoneguarantors.setOpaque(false);

        jLabel17.setForeground(new java.awt.Color(1, 1, 1));
        jLabel17.setText("Address");

        addressguarantors.setForeground(new java.awt.Color(1, 1, 1));
        addressguarantors.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        addressguarantors.setOpaque(false);

        jLabel18.setForeground(new java.awt.Color(1, 1, 1));
        jLabel18.setText("City");

        cityguarantors.setForeground(new java.awt.Color(1, 1, 1));
        cityguarantors.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(11, 19, 102), 2, true));
        cityguarantors.setOpaque(false);

        jLabel19.setForeground(new java.awt.Color(1, 1, 1));
        jLabel19.setText("Age");

        age_guarontores.setBackground(new java.awt.Color(254, 254, 254));
        age_guarontores.setForeground(new java.awt.Color(0, 7, 91));
        age_guarontores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70" }));
        age_guarontores.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(4, 2, 73), 2, true));
        age_guarontores.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                age_guarontoresItemStateChanged(evt);
            }
        });
        age_guarontores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_guarontoresActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(addressguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(cityguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(age_guarontores, 0, 125, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(phoneguarantors, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailguarantors)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(fnameguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(lnameguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(39, 39, 39))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnameguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phoneguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addressguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel19)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(age_guarontores, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel20.setForeground(new java.awt.Color(1, 1, 1));
        jLabel20.setText("Date");

        dateguarantors.setBackground(new java.awt.Color(254, 254, 254));
        dateguarantors.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dateguarantors.setForeground(new java.awt.Color(15, 8, 83));
        dateguarantors.setOpaque(false);

        jButton2.setBackground(new java.awt.Color(255, 3, 0));
        jButton2.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setText("Reset");
        jButton2.setOpaque(true);
        jButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Signature of Guarantor");

        jLabel6.setBackground(new java.awt.Color(142, 137, 137));
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(dateguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateguarantors, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getNumberBalanceBank();
        String total = editammount.getText();
        double d = Double.parseDouble(total);
        double realBalance = Double.parseDouble(av_balance);
        if(d >= 100 && d <= realBalance){
        String sql = "INSERT INTO `Loan`(`loan_id`, `Full_Name_loaner`, `Fullname_guarantors`, `Email_guarantors`, `Ammount`, `Mobile_guarantors`, `Address_guarantors`, `city_guarantors`, `Age_guarantors`, `Date_guarantors`) VALUES (?,?,?,?,?,?,?,?,?,?)";
        try{
            
            String id = acc_no.getSelectedItem().toString();
            String fullname = editfname.getText();
            fullname += " " +editlname.getText();
            String fullnameG = fnameguarantors.getText();
            fullnameG += " " +lnameguarantors.getText();
            
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, id);
            pst.setString(2, fullname);
            pst.setString(3, fullnameG);
            pst.setString(4, emailguarantors.getText());
            pst.setString(5, editammount.getText());
            pst.setString(6, phoneguarantors.getText());
            pst.setString(7, addressguarantors.getText());
            pst.setString(8, cityguarantors.getText());
            pst.setString(9, age_guarontores.getSelectedItem().toString());
            pst.setString(10, dateguarantors.getDateFormatString());
           // stmt = conn.createStatement();
            //stmt.execute(sql);
            pst.execute();
            update_Admin_balance();
            JOptionPane.showMessageDialog(null, "Accepted");
            LoanReceipt l = new LoanReceipt();
            l.setVisible(true);
            l.Accnumber.setText(id);
            l.fanameLoaner.setText(fullname);
            l.fnameG.setText(fullnameG);
            l.EmailG.setText(emailguarantors.getText());
            l.phoneG.setText(phoneguarantors.getText());
            l.cityG.setText(cityguarantors.getText());
            l.AmmountRequested.setText("$"+editammount.getText());
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");  
            LocalDateTime now = LocalDateTime.now();  
            l.DateLoan.setText(dtf.format(now));
            l.AddG.setText(addressguarantors.getText());
            editlname.setText("");
            editfname.setText("");
            fnameguarantors.setText("");
            lnameguarantors.setText("");
            editammount.setText("");
            phoneguarantors.setText("");
            addressguarantors.setText("");
            cityguarantors.setText("");
            dateguarantors.setDateFormatString("");
            
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "please fill details");
            
        }
        }else{
            JDialog dialog = new JDialog();
            dialog.setAlwaysOnTop(true);
            JOptionPane.showMessageDialog(dialog, "Insufficent Ammount",null,JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void acc_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_noActionPerformed
        
    }//GEN-LAST:event_acc_noActionPerformed

    private void acc_noItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_acc_noItemStateChanged
        getIdAll_customer();
    }//GEN-LAST:event_acc_noItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void age_guarontoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_age_guarontoresItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_age_guarontoresItemStateChanged

    private void age_guarontoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_guarontoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_guarontoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loan().setVisible(true);
            }
        });
    }

    public void getIdAll_customer(){
        String getId = acc_no.getSelectedItem().toString();
        try{
            String sql="Select * from Customers where Acc_Number = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, getId);
            rs = pst.executeQuery();
            
            while(rs.next()){
                    String fname = rs.getString("fname");
                    String lname = rs.getString("lname");
                    String gender = rs.getString("Gender");
                    String address = rs.getString("Address");
                    String mobile = rs.getString("Mobile");
                    
                    editfname.setText(fname);
                    editlname.setText(lname);
                    
            }
            rs.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    public void SelectAll_customer(){
        try{
            String sql="Select * from Customers";
            stmt = conn.createStatement();
            rs = stmt.executeQuery(sql);
            
            while(rs.next()){
                String id = rs.getString("Acc_Number");
                acc_no.addItem(id);
            }
            rs.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> acc_no;
    private javax.swing.JTextField addressguarantors;
    private javax.swing.JComboBox<String> age_guarontores;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityguarantors;
    private com.toedter.calendar.JDateChooser dateguarantors;
    private javax.swing.JTextField editammount;
    private javax.swing.JTextField editfname;
    private javax.swing.JTextField editlname;
    private javax.swing.JTextField emailguarantors;
    private javax.swing.JTextField fnameguarantors;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField lnameguarantors;
    private javax.swing.JTextField phoneguarantors;
    // End of variables declaration//GEN-END:variables

    private void update_Admin_balance() {
        try{
            getNumberBalanceBank();
        //String value1 = acc_no.getSelectedItem().toString();
        String value2 = av_balance;
        String newbalance = editammount.getText();
        double no1 = Double.parseDouble(value2);
        double no2 = Double.parseDouble(newbalance);
        double dif = no1-no2;
        String balance = Double.toString(dif);
        String sql ="update Admin set Total_amount = '"+balance+"' where  Admin_id  = 'Admin00001'";
        pst = conn.prepareStatement(sql);
        pst.execute();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "please fill details");
            
        }
    }

    private void getNumberBalanceBank() {
         String sql = "select * from Admin where Admin_id = ?";
        String getuserid = "Admin00001";

        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, getuserid);
            rs = pst.executeQuery();

            while(rs.next()){

                av_balance = rs.getString("Total_amount");
                

            }
        }catch(SQLException e){
            System.out.println(e);
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "please fill details");
            
        }
    }
}
