/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import java.awt.CardLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author aamir
 */
public class UpdateCustomers extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCustomers
     */
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs,rs1;
    PreparedStatement pst,pst1;    
    String id;
    byte[] image =null, image1 =null;
    File file,file1;
   JFileChooser jfc,jfc1;
   String imagepath,imagepath1;
    public UpdateCustomers() {
        initComponents();
        conn = ConnectDB.dbConnector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        Upadate_btn_customer = new javax.swing.JButton();
        withdraw_btn_func4 = new javax.swing.JButton();
        jLabel60 = new javax.swing.JLabel();
        fname_update_cus = new javax.swing.JTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        lname_update_cus = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        dob_update_cus = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        nation_update_cus = new javax.swing.JTextField();
        jLabel65 = new javax.swing.JLabel();
        mobile_update_cus = new javax.swing.JTextField();
        jLabel67 = new javax.swing.JLabel();
        ammount_update_cus = new javax.swing.JTextField();
        jLabel68 = new javax.swing.JLabel();
        add_update_cus = new javax.swing.JTextField();
        jLabel69 = new javax.swing.JLabel();
        gender_update_cus = new javax.swing.JTextField();
        idimage_cus = new javax.swing.JLabel();
        browse_btn1 = new javax.swing.JButton();
        id_update_cus = new javax.swing.JTextField();
        search_btn_update_cus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(7, 58, 210), 2));

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(2, 15, 219)));

        Upadate_btn_customer.setBackground(new java.awt.Color(0, 6, 255));
        Upadate_btn_customer.setForeground(new java.awt.Color(254, 254, 254));
        Upadate_btn_customer.setText("Update");
        Upadate_btn_customer.setOpaque(true);
        Upadate_btn_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upadate_btn_customerActionPerformed(evt);
            }
        });

        withdraw_btn_func4.setBackground(new java.awt.Color(0, 6, 255));
        withdraw_btn_func4.setForeground(new java.awt.Color(254, 254, 254));
        withdraw_btn_func4.setText("Delete");
        withdraw_btn_func4.setOpaque(true);
        withdraw_btn_func4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdraw_btn_func4ActionPerformed(evt);
            }
        });

        jLabel60.setForeground(new java.awt.Color(27, 27, 27));
        jLabel60.setText("ID");

        fname_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        jLabel61.setForeground(new java.awt.Color(27, 27, 27));
        jLabel61.setText("Fname");

        jLabel62.setForeground(new java.awt.Color(27, 27, 27));
        jLabel62.setText("Lname");

        lname_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        jLabel63.setForeground(new java.awt.Color(27, 27, 27));
        jLabel63.setText("DOB");

        dob_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        jLabel64.setForeground(new java.awt.Color(27, 27, 27));
        jLabel64.setText("Nationality");

        nation_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        jLabel65.setForeground(new java.awt.Color(27, 27, 27));
        jLabel65.setText("Mobile");

        mobile_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        jLabel67.setForeground(new java.awt.Color(27, 27, 27));
        jLabel67.setText("Ammount");

        ammount_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        jLabel68.setForeground(new java.awt.Color(27, 27, 27));
        jLabel68.setText("Address");

        add_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        jLabel69.setForeground(new java.awt.Color(27, 27, 27));
        jLabel69.setText("Gender");

        gender_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        idimage_cus.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(2, 5, 253), 3, true));

        browse_btn1.setBackground(new java.awt.Color(0, 6, 255));
        browse_btn1.setForeground(new java.awt.Color(254, 254, 254));
        browse_btn1.setText("Browse");
        browse_btn1.setOpaque(true);
        browse_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browse_btn1ActionPerformed(evt);
            }
        });

        id_update_cus.setForeground(new java.awt.Color(27, 27, 27));

        search_btn_update_cus.setBackground(new java.awt.Color(0, 6, 255));
        search_btn_update_cus.setForeground(new java.awt.Color(254, 254, 254));
        search_btn_update_cus.setText("Search");
        search_btn_update_cus.setOpaque(true);
        search_btn_update_cus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btn_update_cusActionPerformed(evt);
            }
        });

        jLayeredPane4.setLayer(Upadate_btn_customer, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(withdraw_btn_func4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel60, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(fname_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel61, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel62, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(lname_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel63, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(dob_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel64, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(nation_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel65, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(mobile_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel67, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(ammount_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel68, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(add_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel69, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(gender_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(idimage_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(browse_btn1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(id_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(search_btn_update_cus, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lname_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(jLabel63)
                    .addComponent(dob_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(nation_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jLayeredPane4Layout.createSequentialGroup()
                            .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                    .addComponent(jLabel61)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(id_update_cus))
                            .addGap(18, 18, 18)
                            .addComponent(search_btn_update_cus))
                        .addComponent(fname_update_cus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Upadate_btn_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mobile_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ammount_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel68, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel67, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idimage_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel69, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gender_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdraw_btn_func4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(browse_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel60)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(id_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(search_btn_update_cus))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fname_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel62, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idimage_cus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lname_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browse_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addComponent(jLabel63)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dob_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                                .addComponent(jLabel67)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ammount_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel64)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nation_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel68)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(add_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jLabel65, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mobile_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Upadate_btn_customer))
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addComponent(jLabel69)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender_update_cus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(withdraw_btn_func4))))
        );

        jLabel2.setFont(new java.awt.Font("Ubuntu Thin", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(2, 5, 122));
        jLabel2.setText("Upadate Customers");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_filled_cancel_32px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane4)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(19, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Upadate_btn_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upadate_btn_customerActionPerformed
        //update Customer `emp_Number`=?,
        String sql1 ="UPDATE `Customers` SET `fname`=?,`lname`=?,`DOB`=?,`Nationality`=?,`Mobile`=?,`Gender`=?,`image`=?,`Ammount`=?,`Address`=? WHERE Acc_Number=?";
        try {
            InputStream is = new FileInputStream(new File(imagepath1));
            pst1 = conn.prepareStatement(sql1);
            pst1.setString(1, fname_update_cus.getText());
            pst1.setString(2, lname_update_cus.getText());
            pst1.setString(3, dob_update_cus.getText());
            pst1.setString(4, nation_update_cus.getText());
            pst1.setString(5, mobile_update_cus.getText());
            pst1.setString(6, gender_update_cus.getText());
            pst1.setBlob(7, is);
            pst1.setString(8, ammount_update_cus.getText());
            pst1.setString(9, add_update_cus.getText());
            pst1.setString(10, id_update_cus.getText());
            pst1.execute();
            JOptionPane.showMessageDialog(null,"Updated");
            fname_update_cus.setText("");
            lname_update_cus.setText("");
            dob_update_cus.setText("");
            nation_update_cus.setText("");
            mobile_update_cus.setText("");
            gender_update_cus.setText("");
            ammount_update_cus.setText("");
            add_update_cus.setText("");
            //id_update_cus.setText("");
            idimage_cus.setIcon(null);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AdminPanel.class.getName()).log(Level.SEVERE, null, ex);
        }catch (NullPointerException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_Upadate_btn_customerActionPerformed

    private void withdraw_btn_func4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdraw_btn_func4ActionPerformed
        //delete customer
        String sql= "DELETE FROM `Customers` WHERE Acc_Number = ?";
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, id_update_cus.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null,"One record Deleted");
            id_update_cus.setText("");
            fname_update_cus.setText("");
            lname_update_cus.setText("");
            gender_update_cus.setText("");
            mobile_update_cus.setText("");
            dob_update_cus.setText("");
            add_update_cus.setText("");
            nation_update_cus.setText("");
            ammount_update_cus.setText("");
        }catch(Exception e){

        }
    }//GEN-LAST:event_withdraw_btn_func4ActionPerformed

    private void browse_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browse_btn1ActionPerformed
        //browse btn
        //select image
        jfc1=new JFileChooser();
        if(jfc1.showOpenDialog(idimage_cus)==JFileChooser.APPROVE_OPTION){

            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc1.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(idimage_cus.getWidth(),idimage_cus.getHeight(),Image.SCALE_SMOOTH);
            ImageIcon imageIcon=new ImageIcon(imagedResized);

            idimage_cus.setIcon(imageIcon);
            //lblnmfile.setText(jfc.getSelectedFile().getName());

            file1=new File(jfc1.getSelectedFile().getPath());
            String path = jfc1.getSelectedFile().getAbsolutePath();

            //String path=new File(".").getCanonicalPath();
            //FileUtils.copyFileToDirectory(file, new File(path+"/image"));
            imagepath1 = path;
            //System.out.println(s);
        }
    }//GEN-LAST:event_browse_btn1ActionPerformed

    private void search_btn_update_cusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btn_update_cusActionPerformed
        //update_search
        //search the id and set details on the form
        String sql = "select * from Customers where Acc_Number =?";
        String getuserid = id_update_cus.getText();
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, getuserid);
            rs = pst.executeQuery();

            if(rs.next()){
                fname_update_cus.setText(rs.getString("fname"));
                lname_update_cus.setText(rs.getString("lname"));
                ammount_update_cus.setText(rs.getString("Ammount"));
                dob_update_cus.setText(rs.getString("DOB"));
                nation_update_cus.setText(rs.getString("Nationality"));
                mobile_update_cus.setText(rs.getString("Mobile"));
                add_update_cus.setText(rs.getString("Address"));
                gender_update_cus.setText(rs.getString("Gender"));

                //set icon img
                image1 = rs.getBytes("image");
                Image img = Toolkit.getDefaultToolkit().createImage(image1);
                Image imagedResized=img.getScaledInstance(idimage_cus.getWidth(),idimage_cus.getHeight(),Image.SCALE_SMOOTH);
                ImageIcon imageIcon=new ImageIcon(imagedResized);
                idimage_cus.setIcon(imageIcon);
                rs.close();
                pst.close();

            }
            else{
                JDialog dialog = new JDialog();
                dialog.setAlwaysOnTop(true);
                JOptionPane.showMessageDialog(dialog, "please enter your correct account number",null,JOptionPane.WARNING_MESSAGE);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_search_btn_update_cusActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Upadate_btn_customer;
    private javax.swing.JTextField add_update_cus;
    private javax.swing.JTextField ammount_update_cus;
    private javax.swing.JButton browse_btn1;
    private javax.swing.JTextField dob_update_cus;
    private javax.swing.JTextField fname_update_cus;
    private javax.swing.JTextField gender_update_cus;
    private javax.swing.JTextField id_update_cus;
    private javax.swing.JLabel idimage_cus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lname_update_cus;
    private javax.swing.JTextField mobile_update_cus;
    private javax.swing.JTextField nation_update_cus;
    private javax.swing.JButton search_btn_update_cus;
    private javax.swing.JButton withdraw_btn_func4;
    // End of variables declaration//GEN-END:variables
}
